# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  php71:
    docker:
      - image: circleci/php:7.4-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --prefer-source --no-suggest
      - run: php vendor/bin/phpunit --colors=always
  php72:
    docker:
      - image: circleci/php:7.4-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --prefer-source --no-suggest
      - run: php vendor/bin/phpunit --colors=always
  php73:
    docker:
      - image: circleci/php:7.4-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --prefer-source --no-suggest
      - run: php vendor/bin/phpunit --colors=always
  php74:
    docker:
      - image: circleci/php:7.4-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --prefer-source --no-suggest
      - run: php vendor/bin/phpunit --colors=always
  php80:
    docker:
      - image: circleci/php:8.0-cli-node-browsers
    steps:
      - checkout
      - run: php -v
      - run: composer install --no-interaction --prefer-source --no-suggest
      - run: php vendor/bin/phpunit --colors=always
workflows:
  version: 2
  build:
    jobs:
      - php71
      - php72
      - php73
      - php74
      - php80
